[package]
name = "payjoin_ffi"
version = "0.13.0"
license = "MIT OR Apache-2.0"
edition = "2021"

[lib]
crate-type = ["lib", "staticlib", "cdylib"]
name = "payjoin_ffi"

[build-dependencies]
uniffi = { version = "0.25.3", features = ["build"] }

[dev-dependencies]
uniffi = { version = "0.25.3", features = ["bindgen-tests"] }
assert_matches = "1.5.0"
env_logger = "0.10.0"
bitcoind = { version = "0.34.1", features = ["0_21_2"] }


[dependencies]
anyhow = "1.0.70"
env_logger = "0.10.0"
log = "0.4.7"
serde = { version = "1.0.160", features = ["derive"] }
#payjoin = { version = "0.13.0", features = ["send", "receive", "base64", "v2"] }
payjoin = { git= "https://github.com/LtbLightning/rust-payjoin", branch = "ffi",  features = ["send", "receive", "base64", "v2"] }


serde_json = "1.0.103"
uniffi = { version = "0.25.3" }
url = "2.4.0"
thiserror = "1.0.47"
bitcoincore-rpc = "0.18.0"
bitcoin = { version = "0.30.0", features = ["base64"] }
bip21 = "0.3.1"
[[bin]]
name = "uniffi-bindgen"
path = "uniffi-bindgen.rs"

[profile.release-smaller]
inherits = "release"
opt-level = 'z'
lto = true
codegen-units = 1
strip = true


[features]
default = ["uniffi/cli"]
